version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-account"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s75nbu3x24ge"
s3_prefix = "user-account"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

