package com.mybank.aws;

import org.apache.http.HttpStatus;

import com.amazonaws.auth.ClasspathPropertiesFileCredentialsProvider;
import com.amazonaws.services.cognitoidp.AWSCognitoIdentityProvider;
import com.amazonaws.services.cognitoidp.AWSCognitoIdentityProviderClientBuilder;
import com.amazonaws.services.cognitoidp.model.GlobalSignOutRequest;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.google.gson.Gson;
import com.mybank.aws.common.HttpRequest;
import com.mybank.aws.common.HttpResponse;

public class UserCognitoSignoutFunctionHandler implements RequestHandler<HttpRequest, HttpResponse> {
	
	private final String CLIENT_ID = "******";
	private final String USER_POOL_ID = "*****";
	private String endpoint = "*****";
	private String region = "*****";
	Gson gson = new Gson();
	
    @Override
    public HttpResponse handleRequest(HttpRequest request, Context context) {
        context.getLogger().log("Input: " + request);
        String accessToken = request.getHeaders().get("AccessToken");
        
        //String accessToken = "eyJraWQiOiI4YlVjV3dleUxqV1I1SWhoeFBCaXdkRUhyQUJZUytcL0M2WGZOdm0ybUN1bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI4MTU1OWM5NC01YmRmLTRjOWUtYWZiOS0yNGZjZjI0YTA0MWUiLCJldmVudF9pZCI6Ijk0YWE1YzU5LWM1OWUtNGQ0Ny1hMTA5LTE1MjAzNjEzYmQyOSIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1OTg1NDgzNzYsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX1N2MUtkSE9oOCIsImV4cCI6MTU5ODU1MTk3NiwiaWF0IjoxNTk4NTQ4Mzc2LCJqdGkiOiIzNTQwYzc1NC05MWIyLTRmMDItOGNkMC0yMzVlMTdjNWJiM2QiLCJjbGllbnRfaWQiOiI3dGdzZjltN3UyamNlcnZxZXNzNzFyOGxjZCIsInVzZXJuYW1lIjoidXNlcjEifQ.WknYYpjvihyrUX2DosqNT3LWqRXjMWyzw3LmD_KOlE9okfKo7mjzvMMxlboWhRde6NUI6KaTvIDnCJeuT_ecZIM1nUSO_vn-MOx1lt0ANmoljp9j_SOXQGnu7l3lcjsuyYmHzZQxGvFIGFuyfdXBXvpkBqBadZU1n43lqjxPN7MWeZUBOh88gSqxDSNaSthKlaFs--YpEUNNFrXyj0fHifiR_zmoJ9X8hqynXq20XW_7h9OXHSuNUbcCAxI5ESi5eSGN8ipfCi8eyIG3g-9t-JcgzKztot9GR2JKSDHCSMPynmY25cw4Hk15F2GS2p8kajpw5FDpWydm2wBL0U9KoA";
       
        context.getLogger().log("accessToken: " + accessToken);
        AWSCognitoIdentityProvider cognitoClient = getAmazonCognitoIdentityClient();
        GlobalSignOutRequest signoutRequest = new GlobalSignOutRequest();
		signoutRequest.withAccessToken(accessToken);
		
		cognitoClient.globalSignOut(signoutRequest);
		HttpResponse response = new HttpResponse(HttpStatus.SC_OK,"Logged out Successfully");
        return response;
    }
    
    public AWSCognitoIdentityProvider getAmazonCognitoIdentityClient() {
		ClasspathPropertiesFileCredentialsProvider propertiesFileCredentialsProvider = new ClasspathPropertiesFileCredentialsProvider();

		return AWSCognitoIdentityProviderClientBuilder.standard().withCredentials(propertiesFileCredentialsProvider)
				.withRegion(region).build();

	}

}

/*
"accessToken": "eyJraWQiOiI4YlVjV3dleUxqV1I1SWhoeFBCaXdkRUhyQUJZUytcL0M2WGZOdm0ybUN1bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI4MTU1OWM5NC01YmRmLTRjOWUtYWZiOS0yNGZjZjI0YTA0MWUiLCJldmVudF9pZCI6IjBhZDBlODVmLTM5NTctNGY0Ni1hZjU5LThmM2EwZGY4MWJjMiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1OTgzMDc2ODQsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX1N2MUtkSE9oOCIsImV4cCI6MTU5ODMxMTI4NCwiaWF0IjoxNTk4MzA3Njg0LCJqdGkiOiI3YzRmNjU4OC1hZDdlLTRhNmMtYWU2Zi0xMGMzMTM2YTNiZjgiLCJjbGllbnRfaWQiOiI3dGdzZjltN3UyamNlcnZxZXNzNzFyOGxjZCIsInVzZXJuYW1lIjoidXNlcjEifQ.mSvzMit2fKT6m9oAQRvv9FYtva5KRIhJqro-0kANj77zNMCkifpAYYbuM1fEheCMDVPx-3WeYWxH8capQMYzPmGpVsGSwcnQE7FzDjnwpm-A1zcxMIKDJOOS_9MHm8b-GLMi3r5Ipowux0K1vOhIBx3iiErep9uqLSKDk1mnYkjb3rFfUQd0jXmV005M4agy3IPL2yUh4PIegGCpyUtBpi6CtCLm9NpMpy6COoAJd6fuA5RytMD0W2ti3mkXORsrQrhZnbQelt36haLzSEAIsUW7_vm9xe_7M0kLWgig1nR0OFWl4eoxEOQ7bUYdh-lcuWeslgmQyEVYbol73MARfw",
"expiresIn": 3600,
"tokenType": "Bearer",
"refreshToken": "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.PwQLE0gZFSJshZ0fkmCUuVOnDi58m3BPrExYI3W8Hp2-TVa46GxbD9LGxbmttoAvwv6tzU0bctxLMBFwJ5X7EYIwFnfNlFsgXvocwAnNxOdI39m18fF9dGFd6JH9LpeuYNwVYNaEvtnLTD6iZfzDpSffSX5kp2lTwpxhx7fwN2-ShLu8_HwBvLWANWh1DPucgy647JltNTMWHG_DvPJHRD1t6pLAxr2fQw2wBbnMPKzo59U5_FT_atsgI4IeHv8WYczMJXFX70ykIjD_gcGhXnZdBtLM3sW1P4Qu-4Z078Up_oaGmwpsOzaZex8-UxR4NkDz6G4x6BYlc6mvJN4OPg.Wz6JIbiZY6fqxb0x.t1bcWBuLW874qma_JQrdnCGzCNflHhuWHl4SHCwg89_gUsu_Xr4Yxid68m3FYHBf_nuWXizLy8rYT_cvu3nYHtnsC97QU2JNVkkd2MF8cg7_vd5w7KYyt-vIM1kqU5vsu2-tAe71P1fT92_RRMcpzDvIHw-6Ho-bwpJftFbf07ZBqA--e0zpNZwqs6Dwa2iyUT0ZA1AusQbXYY1HHg4d_IDuAVfUvWouhpj-HNm20vYqbgmidEhHaWhpoWiWYyTnjm3xu3D2ImiDKstug-T4UxDyPsTQ5_XNpjTKlOWt_4GpFelpjsLKQv0EPwMwj_96LyMbyYiNjpxe2Q4_XXN3d9nzvcWLuuBvEuFzsu9LqAZSM70cgUu8raVpvfwowMRO6TIbR4-WX0tGHXLE2XsMkBA2jzddYKS3RBubohWtelU3tYFo9ZALYri_llej_Qi7GX3128cCMAu-7iJShRX7qUeJZfgidOrwppirxY4Ig1RpQHArcXX0_rWyrv5E6H8AF32i6MveBSIqxdlwQd37moY1gic_h9b7Dp7U04YFy5Wwy6T7NVBxWRZc3VNN76Z2HRnP1u_tBFFnO-kyU0YTjS3l20YQWccUvnnq71rzqriFxIMP8LRo80VljX3uP8jcOxDAQdP1RIMPwcMdt75Hs2Nmlpv1vqGaTZy3XyWDM5VtUD8EA5dJt-BuBSmGpBR-ghYtYd83mHXJFMvWgCJQVDHgrXYsD7DCFFB_P79LSNfNjyH79WeZMH4CrIqLlK7iXmPKA-nPqHgY-O9kM7ss_djFm7Zt5IQSq8Vctthe-DZ6SLFP3paVcCFClBZoNPxdQnBNiGSsKcID5v3bnFpr5iU6oKzATzBW7f-MA1BcjQXs9ppS592ghu_wk-nj57vAXJpo5r19WBryNDGcUmp0DwOMA1KUI_-y_70MmszEMCwZ5x_B3tg9WwOmJWTyWIQJ6qLzVKMWWOVzsRm7ZoS5oZdMkI7kFjRMZAAxB8nZ717cJkw4nb1OFVveH4agqSID2zbXlRDeqFCcEyvC52mlZwCRi3Z-mHp9LPTdhLFUOL9brijSUdqKP_PftUz8QHZ5Vgz_hmxupDu0h-JyRdAgSlcpb6vgg5WZvzDlXlgTN65SJ4vuhX-wJnYQeGpmgfkmRtXSE-aHzbnTg2vL5n_IKhDVVBUh3ClDy6zZ6f2eA_8aRuJNpu0k3_Zme_drD3cTzQlrBQhbgkQK01Y5DU2mYMEoP7HZ3GWFOtp6AhRVwbeP7_JUgSqmZBk-uwt6vS7GVEQ.3ibxK1OdU_ji8txB9D6JTQ",
"idToken": "eyJraWQiOiJXWXF4WEtRY2Q0MnU1cm1WWm1WZ0pqK0pHcVpRQUxLQVwvZGRDVk9nU2V2VT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI4MTU1OWM5NC01YmRmLTRjOWUtYWZiOS0yNGZjZjI0YTA0MWUiLCJhdWQiOiI3dGdzZjltN3UyamNlcnZxZXNzNzFyOGxjZCIsImV2ZW50X2lkIjoiMGFkMGU4NWYtMzk1Ny00ZjQ2LWFmNTktOGYzYTBkZjgxYmMyIiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE1OTgzMDc2ODQsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX1N2MUtkSE9oOCIsImNvZ25pdG86dXNlcm5hbWUiOiJ1c2VyMSIsImV4cCI6MTU5ODMxMTI4NCwiaWF0IjoxNTk4MzA3Njg0LCJlbWFpbCI6InN3YXBuaWwua290aGF3YWRlQGdtYWlsLmNvbSJ9.CsQfvrMu-nY1eS_6GalcB8-8Y4edaPU-zW6rVuDpahUvfbOSpnt_q0SgYT6dhBGAzvB_9VqPo0N4tg4wyTpPp9qErqY3cU1FTMh80FM_MyKvFJ82WYzhLT-_ZfQrXkv_gqwomxHuQNy9zoEJHa9WgJb4xZ6_g1gTP-mAzo5Mtu3Xnzb6Lvq0sYiGp9hJYsXnZKzyz0afIOTovMf0G85je2XdqkrWAMXasTvJ3FXaQ5ENbKz5U7x8lgmCcdy3y6hvuq_cciguKkZM1aTcH72lLOjrhrK69zBa9CxbVrXorTlbUCJcPqWZt7cB6tNo-5X2TwL-Ff0TNm0QylWUaR6GJA"
}*/
