AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Allow User to apply loan
Resources:
  UserLoanFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: com.mybank.aws.UserLoanFunctionHandler
      Runtime: java8
      CodeUri: .
      Description: Allow User to apply loan
      MemorySize: 512
      Timeout: 15
      Role: 'arn:aws:iam::381233585660:role/basic_lambda_s3_apigateway_role'
      